In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
C:\anaconda3\envs\my_env\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\anaconda3\envs\my_env\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\anaconda3\envs\my_env\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
df = pd.read_csv('survey_results_public.csv')
df = df[['Country','EdLevel','YearsCodePro','Employment','ConvertedComp']]
df = df.rename({'ConvertedComp':'Salary'},axis=1)
df = df[df['Salary'].notnull()]
df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 34756 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       34756 non-null  object 
 1   EdLevel       34188 non-null  object 
 2   YearsCodePro  34621 non-null  object 
 3   Employment    34717 non-null  object 
 4   Salary        34756 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB
df = df.dropna()
df = df[df['Employment'] == 'Employed full-time']
df = df.drop('Employment',axis=1)
df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30019 entries, 7 to 64154
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       30019 non-null  object 
 1   EdLevel       30019 non-null  object 
 2   YearsCodePro  30019 non-null  object 
 3   Salary        30019 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.1+ MB
(df['Country'].value_counts())
United States     7569
India             2425
United Kingdom    2287
Germany           1903
Canada            1178
                  ... 
Belize               1
Namibia              1
Swaziland            1
San Marino           1
Guinea               1
Name: Country, Length: 154, dtype: int64
def clean_data(col,threshold):
    countries = {}
    for i in range(len(col)):
        if col.values[i] >= threshold:
            countries[col.index[i]] = col.index[i]
        else:
            countries[col.index[i]] = 'Other'
    return countries
country_map = clean_data(df['Country'].value_counts(),400)
country_map
{'United States': 'United States',
 'India': 'India',
 'United Kingdom': 'United Kingdom',
 'Germany': 'Germany',
 'Canada': 'Canada',
 'Brazil': 'Brazil',
 'France': 'France',
 'Spain': 'Spain',
 'Australia': 'Australia',
 'Netherlands': 'Netherlands',
 'Poland': 'Poland',
 'Italy': 'Italy',
 'Russian Federation': 'Russian Federation',
 'Sweden': 'Sweden',
 'Turkey': 'Other',
 'Israel': 'Other',
 'Pakistan': 'Other',
 'Switzerland': 'Other',
 'Mexico': 'Other',
 'Ireland': 'Other',
 'Norway': 'Other',
 'Ukraine': 'Other',
 'Romania': 'Other',
 'South Africa': 'Other',
 'Czech Republic': 'Other',
 'Austria': 'Other',
 'Belgium': 'Other',
 'Iran': 'Other',
 'Portugal': 'Other',
 'Denmark': 'Other',
 'Finland': 'Other',
 'Argentina': 'Other',
 'Hungary': 'Other',
 'New Zealand': 'Other',
 'Greece': 'Other',
 'Japan': 'Other',
 'Bangladesh': 'Other',
 'Bulgaria': 'Other',
 'Colombia': 'Other',
 'Serbia': 'Other',
 'Philippines': 'Other',
 'Indonesia': 'Other',
 'Nigeria': 'Other',
 'Singapore': 'Other',
 'Lithuania': 'Other',
 'Sri Lanka': 'Other',
 'Chile': 'Other',
 'China': 'Other',
 'Viet Nam': 'Other',
 'Croatia': 'Other',
 'Malaysia': 'Other',
 'Estonia': 'Other',
 'Slovenia': 'Other',
 'Egypt': 'Other',
 'South Korea': 'Other',
 'Nepal': 'Other',
 'Taiwan': 'Other',
 'Belarus': 'Other',
 'Slovakia': 'Other',
 'Latvia': 'Other',
 'Uruguay': 'Other',
 'United Arab Emirates': 'Other',
 'Kenya': 'Other',
 'Peru': 'Other',
 'Hong Kong (S.A.R.)': 'Other',
 'Thailand': 'Other',
 'Dominican Republic': 'Other',
 'Bosnia and Herzegovina': 'Other',
 'Iceland': 'Other',
 'Costa Rica': 'Other',
 'Kazakhstan': 'Other',
 'Malta': 'Other',
 'Cyprus': 'Other',
 'Republic of Korea': 'Other',
 'Lebanon': 'Other',
 'Ghana': 'Other',
 'Morocco': 'Other',
 'Jordan': 'Other',
 'Venezuela, Bolivarian Republic of...': 'Other',
 'Tunisia': 'Other',
 'Armenia': 'Other',
 'Georgia': 'Other',
 'Ecuador': 'Other',
 'Guatemala': 'Other',
 'Uganda': 'Other',
 'Luxembourg': 'Other',
 'Albania': 'Other',
 'Republic of Moldova': 'Other',
 'Bolivia': 'Other',
 'Nicaragua': 'Other',
 'Saudi Arabia': 'Other',
 'Azerbaijan': 'Other',
 'Afghanistan': 'Other',
 'El Salvador': 'Other',
 'Paraguay': 'Other',
 'Myanmar': 'Other',
 'Ethiopia': 'Other',
 'Cuba': 'Other',
 'Algeria': 'Other',
 'Kosovo': 'Other',
 'Panama': 'Other',
 'The former Yugoslav Republic of Macedonia': 'Other',
 'Uzbekistan': 'Other',
 'Honduras': 'Other',
 'Iraq': 'Other',
 'Qatar': 'Other',
 'Zimbabwe': 'Other',
 'Nomadic': 'Other',
 'Kyrgyzstan': 'Other',
 'Jamaica': 'Other',
 'Cambodia': 'Other',
 'Mauritius': 'Other',
 'Madagascar': 'Other',
 'Sudan': 'Other',
 'Montenegro': 'Other',
 'Cameroon': 'Other',
 'Trinidad and Tobago': 'Other',
 'United Republic of Tanzania': 'Other',
 'Bhutan': 'Other',
 'Bahrain': 'Other',
 'Mongolia': 'Other',
 'Isle of Man': 'Other',
 'Syrian Arab Republic': 'Other',
 'Oman': 'Other',
 'Kuwait': 'Other',
 'Botswana': 'Other',
 'Rwanda': 'Other',
 'Togo': 'Other',
 'Haiti': 'Other',
 'Zambia': 'Other',
 'Maldives': 'Other',
 'Guyana': 'Other',
 "Lao People's Democratic Republic": 'Other',
 'Angola': 'Other',
 "Côte d'Ivoire": 'Other',
 'Democratic Republic of the Congo': 'Other',
 'Somalia': 'Other',
 'Mauritania': 'Other',
 'Turkmenistan': 'Other',
 'Fiji': 'Other',
 'Benin': 'Other',
 'Monaco': 'Other',
 'Saint Vincent and the Grenadines': 'Other',
 'Bahamas': 'Other',
 'Senegal': 'Other',
 'Andorra': 'Other',
 'Barbados': 'Other',
 'Yemen': 'Other',
 'Niger': 'Other',
 'Belize': 'Other',
 'Namibia': 'Other',
 'Swaziland': 'Other',
 'San Marino': 'Other',
 'Guinea': 'Other'}
df['Country'] = df['Country'].map(country_map)
df['Country'].value_counts()
Other                 8549
United States         7569
India                 2425
United Kingdom        2287
Germany               1903
Canada                1178
Brazil                 991
France                 972
Spain                  670
Australia              659
Netherlands            654
Poland                 566
Italy                  560
Russian Federation     522
Sweden                 514
Name: Country, dtype: int64
import seaborn as sns
fig = plt.figure(figsize = (15,10))
sns.boxplot(x = df['Country'], y = df['Salary'])
<AxesSubplot:xlabel='Country', ylabel='Salary'>

df = df[df['Salary'] <= 250000]
df = df[df['Salary'] >= 10000]
df = df[df['Country'] != 'Other']
fig = plt.figure(figsize = (15,10))
sns.boxplot(x = df['Country'], y = df['Salary'])
<AxesSubplot:xlabel='Country', ylabel='Salary'>

df['YearsCodePro'].unique()
array(['13', '4', '2', '7', '20', '1', '3', '10', '12', '29', '6', '28',
       '8', '23', '15', '25', '9', '11', 'Less than 1 year', '5', '21',
       '16', '18', '14', '32', '19', '22', '38', '30', '26', '27', '17',
       '24', '34', '35', '33', '36', '40', '39', 'More than 50 years',
       '31', '37', '41', '45', '42', '44', '43', '50', '49'], dtype=object)
def clean_experience(col):
    if col == 'More than 50 years':
        return 50
    if col == 'Less than 1 year':
        return 0.5
    return float(col)
df['Experience'] = df['YearsCodePro'].apply(clean_experience)
df = df.drop('YearsCodePro',axis=1)
df['EdLevel'].unique()
array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'I never completed any formal education',
       'Primary/elementary school'], dtype=object)
def clean_education_level(col):
    if "Bachelor’s degree" in col:
        return 'Bachelor’s degree'
    if "Master’s degree" in col:
        return "Master’s degree"
    if 'Professional degree' in col or 'Other doctoral' in col:
        return 'Post Grad'
    return 'Less than a bachelors'
df['Education_Level'] = df['EdLevel'].apply(clean_education_level)
df = df.drop('EdLevel',axis=1)
df['Education_Level'].unique()
array(['Bachelor’s degree', 'Master’s degree', 'Less than a bachelors',
       'Post Grad'], dtype=object)
from sklearn.preprocessing import LabelEncoder
edu_level = LabelEncoder()
df['Education_Level']  = edu_level.fit_transform(df['Education_Level'])
df['Education_Level'].unique()
array([0, 2, 1, 3])
countries_le = LabelEncoder()

df['Country'] = countries_le.fit_transform(df['Country'])
df['Country'].unique()
array([13, 12, 10,  7,  4,  2,  6,  1,  3,  5, 11,  8,  0,  9])
MAKING MODEL
X = df.drop("Salary",axis=1)
y = df['Salary']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
from sklearn.linear_model import LinearRegression
reg_model = LinearRegression()
reg_model.fit(X_train,y_train)
LinearRegression()
y_pred = reg_model.predict(X_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error
error1 = mean_absolute_error(y_test,y_pred)
error2 = np.sqrt(mean_squared_error(y_test,y_pred))
print(error1,error2)
30054.06797109598 38530.67398101534
from sklearn.tree import DecisionTreeRegressor
tree_model = DecisionTreeRegressor(random_state = 0)
tree_model.fit(X_train,y_train)
DecisionTreeRegressor(random_state=0)
y_pred = tree_model.predict(X_test)
error1 = mean_absolute_error(y_test,y_pred)
error2 = np.sqrt(mean_squared_error(y_test,y_pred))
print(error1,error2)
22064.512358943688 32140.777586789416
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor(random_state = 0)
forest_model.fit(X_train,y_train)
RandomForestRegressor(random_state=0)
y_pred = forest_model.predict(X_test)
error1 = mean_absolute_error(y_test,y_pred)
error2 = np.sqrt(mean_squared_error(y_test,y_pred))
print(error1,error2)
21848.889987177543 31764.697100561007
from sklearn.model_selection import GridSearchCV
max_depth = [None,2,4,6,8,10,12]
param_grid = {'max_depth':max_depth}
regressor = RandomForestRegressor(random_state = 0)
gs = GridSearchCV(regressor,param_grid,scoring = 'neg_mean_squared_error')
gs.fit(X_train,y_train)
GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')
regressor = gs.best_estimator_
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
error = np.sqrt(mean_squared_error(y_test, y_pred))
print("${:,.02f}".format(error))
$30,946.95
X
Country	Experience	Education_Level
7	13	13.0	0
9	12	4.0	2
10	12	2.0	0
11	10	7.0	1
12	7	20.0	1
...	...	...	...
64113	13	15.0	1
64116	13	6.0	0
64122	13	4.0	1
64127	13	12.0	3
64129	13	4.0	2
18491 rows × 3 columns

ip = np.array([['United States','Master’s degree',15]])
ip
array([['United States', 'Master’s degree', '15']], dtype='<U15')
ip[:,0] = countries_le.transform(ip[:,0])
ip[:,1] = edu_level.transform(ip[:,1])
ip = ip.astype(float)
prediction = regressor.predict(ip)
prediction
array([108640.51967989])
import pickle
data = {'model':regressor,'le_country':countries_le,'le_education':edu_level}
with open('saved_step.pkl','wb') as file:
    pickle.dump(data,file)
with open('saved_step.pkl','rb') as file:
    data = pickle.load(file)
loaded_regressor = data['model']
le_country = data['le_country']
le_edu  = data['le_education']
pred = loaded_regressor.predict(ip)
pred
array([108640.51967989])
df['Country'].unique()
array([13, 12, 10,  7,  4,  2,  6,  1,  3,  5, 11,  8,  0,  9])